networks:
  default: local-bsc-fork
  local-bsc-fork:
    pancake_pair: "0x58F876857a02D6762E0101bb5C46A8c1ED44Dc16"
    pancake_factory: "0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73"
    pancake_router: "0x10ED43C718714eb63d5aA57B78B54704E256024E"

autofetch_sources: false
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.0.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.0.0"
